# Generated by Django 4.1.1 on 2023-11-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('room_id', models.IntegerField(db_column='room_id', unique=True)),
                ('construction_name', models.TextField(db_column='construction_name')),
                ('x_length', models.SmallIntegerField(db_column='x_length')),
                ('y_length', models.SmallIntegerField(db_column='y_length')),
                ('information', models.TextField(db_column='information')),
            ],
        ),
        migrations.CreateModel(
            name='SetTimerHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(db_column='time')),
                ('timer', models.IntegerField(db_column='timer')),
                ('temperature', models.IntegerField(db_column='temperature')),
                ('status', models.IntegerField(db_column='status')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Refering to room that this is trying to set timer value for')),
            ],
        ),
        migrations.CreateModel(
            name='SensorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id')),
                ('co2', models.SmallIntegerField(db_column='co2', null=True)),
                ('temp', models.FloatField(db_column='temp', null=True)),
                ('hum', models.FloatField(db_column='hum', null=True)),
                ('light', models.FloatField(db_column='light', null=True)),
                ('dust', models.FloatField(db_column='dust', null=True)),
                ('sound', models.FloatField(db_column='sound', null=True)),
                ('red', models.SmallIntegerField(db_column='red', null=True)),
                ('green', models.SmallIntegerField(db_column='green', null=True)),
                ('blue', models.SmallIntegerField(db_column='blue', null=True)),
                ('tvoc', models.SmallIntegerField(db_column='tvoc', null=True)),
                ('motion', models.SmallIntegerField(db_column='motion', null=True)),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id')),
                ('x_axis', models.IntegerField(db_column='x_axis')),
                ('y_axis', models.IntegerField(db_column='y_axis')),
                ('function', models.TextField(db_column='function')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
        migrations.CreateModel(
            name='RawSensorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id')),
                ('co2', models.SmallIntegerField(db_column='co2', null=True)),
                ('temp', models.FloatField(db_column='temp', null=True)),
                ('hum', models.FloatField(db_column='hum', null=True)),
                ('light', models.FloatField(db_column='light', null=True)),
                ('dust', models.FloatField(db_column='dust', null=True)),
                ('sound', models.FloatField(db_column='sound', null=True)),
                ('red', models.SmallIntegerField(db_column='red', null=True)),
                ('green', models.SmallIntegerField(db_column='green', null=True)),
                ('blue', models.SmallIntegerField(db_column='blue', null=True)),
                ('tvoc', models.SmallIntegerField(db_column='tvoc', null=True)),
                ('motion', models.SmallIntegerField(db_column='motion', null=True)),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
        migrations.CreateModel(
            name='RawActuatorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id')),
                ('speed', models.SmallIntegerField(db_column='speed')),
                ('state', models.SmallIntegerField(db_column='state')),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
        migrations.CreateModel(
            name='ControlSetpoint',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id', null=True)),
                ('option', models.TextField(db_column='option')),
                ('aim', models.TextField(db_column='aim')),
                ('value', models.FloatField(db_column='value')),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Refering to room that this is trying to set value for')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('node_id', models.IntegerField(db_column='node_id')),
                ('speed', models.SmallIntegerField(db_column='speed')),
                ('state', models.SmallIntegerField(db_column='state')),
                ('time', models.BigIntegerField(db_column='time')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented')),
            ],
        ),
    ]
