# Generated by Django 4.1.1 on 2023-10-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='information',
            field=models.TextField(db_column='information', default='C1B 103'),
            preserve_default=False,
        ),
    ]
