# Generated by Django 4.1.1 on 2023-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settimerhistory',
            name='temperature',
            field=models.IntegerField(db_column='temperature', default=24),
            preserve_default=False,
        ),
    ]
