# Generated by Django 4.1.1 on 2023-12-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_weatherdata_remove_controlsetpoint_aim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuatormonitor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rawactuatormonitor',
            name='state',
        ),
        migrations.AddField(
            model_name='actuatormonitor',
            name='device_type',
            field=models.TextField(db_column='device_type', default='air'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actuatormonitor',
            name='temp',
            field=models.SmallIntegerField(db_column='temp', default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawactuatormonitor',
            name='device_type',
            field=models.TextField(db_column='device_type', default='air'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawactuatormonitor',
            name='temp',
            field=models.SmallIntegerField(db_column='temp', default=25),
            preserve_default=False,
        ),
    ]
