# Generated by Django 4.1.1 on 2023-08-31 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('function', models.TextField(db_column='function')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('construction_name', models.TextField(db_column='construction_name')),
                ('x_length', models.SmallIntegerField(db_column='x_length')),
                ('y_length', models.SmallIntegerField(db_column='y_length')),
            ],
        ),
        migrations.CreateModel(
            name='SensorMonitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co2', models.SmallIntegerField(db_column='co2', null=True)),
                ('temp', models.FloatField(db_column='temp', null=True)),
                ('hum', models.FloatField(db_column='hum', null=True)),
                ('light', models.FloatField(db_column='light', null=True)),
                ('dust', models.FloatField(db_column='dust', null=True)),
                ('sound', models.FloatField(db_column='sound', null=True)),
                ('red', models.SmallIntegerField(db_column='red', null=True)),
                ('green', models.SmallIntegerField(db_column='green', null=True)),
                ('blue', models.SmallIntegerField(db_column='blue', null=True)),
                ('tvoc', models.SmallIntegerField(db_column='tvoc', null=True)),
                ('motion', models.SmallIntegerField(db_column='motion', null=True)),
                ('time', models.BigIntegerField(db_column='time')),
                ('node_id', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Refering to id of room where this node is emplemented'),
        ),
        migrations.CreateModel(
            name='RawSensorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('co2', models.SmallIntegerField(db_column='co2', null=True)),
                ('temp', models.FloatField(db_column='temp', null=True)),
                ('hum', models.FloatField(db_column='hum', null=True)),
                ('light', models.FloatField(db_column='light', null=True)),
                ('dust', models.FloatField(db_column='dust', null=True)),
                ('sound', models.FloatField(db_column='sound', null=True)),
                ('red', models.SmallIntegerField(db_column='red', null=True)),
                ('green', models.SmallIntegerField(db_column='green', null=True)),
                ('blue', models.SmallIntegerField(db_column='blue', null=True)),
                ('tvoc', models.SmallIntegerField(db_column='tvoc', null=True)),
                ('motion', models.SmallIntegerField(db_column='motion', null=True)),
                ('time', models.BigIntegerField(db_column='time')),
                ('node_id', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table')),
            ],
        ),
        migrations.CreateModel(
            name='RawActuatorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('speed', models.SmallIntegerField(db_column='speed')),
                ('state', models.SmallIntegerField(db_column='state')),
                ('time', models.BigIntegerField(db_column='time')),
                ('node_id', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table')),
            ],
        ),
        migrations.CreateModel(
            name='ControlSetpoint',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('option', models.TextField(db_column='option')),
                ('aim', models.TextField(db_column='aim')),
                ('value', models.FloatField(db_column='value')),
                ('time', models.BigIntegerField(db_column='time')),
                ('node_id', models.ForeignKey(db_column='node_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='Refering to node that this is trying to set value for')),
                ('room_id', models.ForeignKey(db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Refering to room that this is trying to set value for')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorMonitor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('speed', models.SmallIntegerField(db_column='speed')),
                ('state', models.SmallIntegerField(db_column='state')),
                ('time', models.BigIntegerField(db_column='time')),
                ('node_id', models.ForeignKey(db_column='node_id', on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table')),
            ],
        ),
    ]
