# Generated by Django 4.1.1 on 2023-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mac',
            field=models.TextField(db_column='mac', default='AB:CD:EF'),
            preserve_default=False,
        ),
    ]
