# Generated by Django 4.1.1 on 2023-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConfigBuffer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('action', models.IntegerField(db_column='action')),
                ('mac', models.TextField(db_column='mac')),
                ('room_id', models.IntegerField(db_column='room_id')),
                ('time', models.BigIntegerField(db_column='time')),
            ],
        ),
    ]
