# Generated by Django 4.1.1 on 2023-11-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nodeconfigbuffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfigbuffer',
            name='mac',
            field=models.TextField(db_column='mac', unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mac',
            field=models.TextField(db_column='mac', unique=True),
        ),
    ]
