# Generated by Django 4.1.1 on 2023-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aqiref'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqiref',
            name='aqi',
            field=models.IntegerField(db_column='aqi', null=True),
        ),
    ]
