# Generated by Django 4.1.1 on 2023-12-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aqiref_aqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mac',
            field=models.TextField(db_column='mac'),
        ),
    ]
