# Generated by Django 4.1.1 on 2024-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_actuatormonitor_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfigbuffer',
            name='mac',
            field=models.TextField(db_column='mac'),
        ),
    ]
