# Generated by Django 4.1.1 on 2023-05-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorMonitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField()),
                ('speed', models.SmallIntegerField()),
                ('state', models.SmallIntegerField()),
                ('time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorMonitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('node_id', models.IntegerField()),
                ('co2', models.SmallIntegerField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('time', models.BigIntegerField()),
            ],
        ),
    ]
