# Generated by Django 4.1.1 on 2023-05-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('macAddress', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='actuatormonitor',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table'),
        ),
        migrations.AlterField(
            model_name='sensormonitor',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='refering to id of node registered in Registration table'),
        ),
    ]
