# Generated by Django 4.1.1 on 2023-05-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration_alter_actuatormonitor_node_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='macAddress',
            new_name='mac_address',
        ),
    ]
