# Generated by Django 4.1.1 on 2023-06-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_macaddress_registration_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSetpoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.TextField()),
                ('aim', models.TextField()),
                ('value', models.FloatField()),
                ('time', models.BigIntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registration', verbose_name='Refering to value that need to set for actuator')),
            ],
        ),
    ]
